"""first_revision

Revision ID: 460f7344e6d7
Revises: 26bd24a56853
Create Date: 2023-07-26 18:52:03.739436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460f7344e6d7'
down_revision = '26bd24a56853'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
